name: ci

on:
  push:
  pull_request:

jobs:
  build-python-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ingestor, event-gen, alert-webhook]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: services/${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import app modules
        working-directory: services/${{ matrix.service }}
        run: |
          python - << 'PY'
          import importlib.util
          spec = importlib.util.spec_from_file_location("main", "main.py")
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          print("Loaded:", getattr(mod, 'app', 'ok'))
          PY

  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install & build
        working-directory: services/analyst-ui
        run: |
          npm ci || npm install
          npm run build
